[2022-05-13 16:14:58,329] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop scheduled__2022-05-12T00:00:00+00:00 [queued]>
[2022-05-13 16:14:58,340] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop scheduled__2022-05-12T00:00:00+00:00 [queued]>
[2022-05-13 16:14:58,341] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-13 16:14:58,341] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-13 16:14:58,341] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-13 16:14:58,460] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_after_loop> on 2022-05-12 00:00:00+00:00
[2022-05-13 16:14:58,462] {standard_task_runner.py:52} INFO - Started process 4964 to run task
[2022-05-13 16:14:58,466] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', 'scheduled__2022-05-12T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', '/usr/local/lib/python3.10/dist-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpy6jq49jd', '--error-file', '/tmp/tmpsv83r04q']
[2022-05-13 16:14:58,466] {standard_task_runner.py:80} INFO - Job 28: Subtask run_after_loop
[2022-05-13 16:14:58,516] {task_command.py:369} INFO - Running <TaskInstance: example_bash_operator.run_after_loop scheduled__2022-05-12T00:00:00+00:00 [running]> on host roshan-Latitude-E5440
[2022-05-13 16:14:58,585] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-12T00:00:00+00:00
[2022-05-13 16:14:58,586] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-13 16:14:58,586] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo 1']
[2022-05-13 16:14:58,591] {subprocess.py:85} INFO - Output:
[2022-05-13 16:14:58,592] {subprocess.py:92} INFO - 1
[2022-05-13 16:14:58,593] {subprocess.py:96} INFO - Command exited with return code 0
[2022-05-13 16:14:58,622] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20220512T000000, start_date=20220513T104458, end_date=20220513T104458
[2022-05-13 16:14:58,677] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-13 16:14:58,697] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
