[2022-05-13 17:01:24,853] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-05-13T11:31:11.197884+00:00 [queued]>
[2022-05-13 17:01:24,868] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-05-13T11:31:11.197884+00:00 [queued]>
[2022-05-13 17:01:24,868] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-13 17:01:24,869] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-13 17:01:24,869] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-13 17:01:24,899] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): also_run_this> on 2022-05-13 11:31:11.197884+00:00
[2022-05-13 17:01:24,901] {standard_task_runner.py:52} INFO - Started process 8968 to run task
[2022-05-13 17:01:24,904] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'also_run_this', 'manual__2022-05-13T11:31:11.197884+00:00', '--job-id', '38', '--raw', '--subdir', '/usr/local/lib/python3.10/dist-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmp2l8v3l1w', '--error-file', '/tmp/tmp7if6_qst']
[2022-05-13 17:01:24,905] {standard_task_runner.py:80} INFO - Job 38: Subtask also_run_this
[2022-05-13 17:01:24,961] {task_command.py:369} INFO - Running <TaskInstance: example_bash_operator.also_run_this manual__2022-05-13T11:31:11.197884+00:00 [running]> on host roshan-Latitude-E5440
[2022-05-13 17:01:25,042] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-05-13T11:31:11.197884+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-13T11:31:11.197884+00:00
[2022-05-13 17:01:25,045] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-13 17:01:25,046] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "run_id=manual__2022-05-13T11:31:11.197884+00:00 | dag_run=<DagRun example_bash_operator @ 2022-05-13 11:31:11.197884+00:00: manual__2022-05-13T11:31:11.197884+00:00, externally triggered: True>"']
[2022-05-13 17:01:25,054] {subprocess.py:85} INFO - Output:
[2022-05-13 17:01:25,054] {subprocess.py:92} INFO - run_id=manual__2022-05-13T11:31:11.197884+00:00 | dag_run=<DagRun example_bash_operator @ 2022-05-13 11:31:11.197884+00:00: manual__2022-05-13T11:31:11.197884+00:00, externally triggered: True>
[2022-05-13 17:01:25,055] {subprocess.py:96} INFO - Command exited with return code 0
[2022-05-13 17:01:25,086] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20220513T113111, start_date=20220513T113124, end_date=20220513T113125
[2022-05-13 17:01:25,116] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-13 17:01:25,148] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
